#!/bin/bash
. /etc/wptt/.wptt.conf
wptangtocols_version=$(curl -s https://raw.githubusercontent.com/hncore/wptangtoc-ols/refs/heads/main/version-wptangtoc-ols.txt?domain-update-tu-dong=$Website_chinh)
if [[ "$wptangtocols_version" != "$version_wptangtoc_ols" ]]; then
    cd
    wget -q https://github.com/hncore/wptangtoc-ols/raw/refs/heads/main/wptangtoc-ols.zip
    unzip -o wptangtoc-ols.zip
    \cp -rf tool-wptangtoc-ols/* /etc/wptt/
    rm -f wptangtoc-ols.zip
    rm -rf tool-wptangtoc-ols
    chmod -R 740 /etc/wptt
    \cp -f /etc/wptt/wptangtoc /usr/bin
    rm -f /etc/wptt/wptangtoc
    \cp -f /etc/wptt/wptt /usr/bin
    rm -f /etc/wptt/wptt
    sed -i "/version_wptangtoc_ols/d" /etc/wptt/.wptt.conf
    echo "version_wptangtoc_ols=$wptangtocols_version" >>/etc/wptt/.wptt.conf
	echo "$wptangtocols_version" > /tmp/wptangtoc-ols-version
    curl -sO https://github.com/hncore/wptangtoc-ols/raw/refs/heads/main/update && bash update
    rm -f update
fi
