#!/bin/bash

wptangtocols_version=$(curl -s https://raw.githubusercontent.com/hncore/wptangtoc-ols/refs/heads/main/version-wptangtoc-ols.txt?kiem-tra-version-crond| head -1 | grep '\.')
if [[ $wptangtocols_version = "" ]];then
wptangtocols_version=$(curl -s https://raw.githubusercontent.com/hncore/wptangtoc-ols/refs/heads/main/version-wptangtoc-ols.txt)
fi

if [[ $wptangtocols_version ]];then
echo "$wptangtocols_version" > /tmp/wptangtoc-ols-version
fi
