#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh
echo ""
echo ""
echo ""
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
echo "========================================================================="
echo "|$quan_ly_update => $cap_nhat PhpMyAdmin                                  |"
echo "========================================================================="
echo ""
fi

if [[ $check_menu_wptangtoc_active = "97" ]];then
echo "========================================================================="
echo "|$quan_ly_phpmyadmin => $cap_nhat PhpMyAdmin                              |"
echo "========================================================================="
echo ""
fi

. /etc/wptt/echo-color
if [[ $id_dang_nhap_phpmyadmin = "" || ( ! -d /usr/local/lsws/$Website_chinh/html/web/phpmyadmin && ! -d /usr/local/lsws/$Website_chinh/html/phpmyadmin ) ]]; then
echoDo "$ban_chua_kich_hoat PhpMyAdmin"
sleep 3
    . /etc/wptt/wptt-phpmyadmin-main 1
exit
fi

if [[ -d /usr/local/lsws/$Website_chinh/html/web/phpmyadmin ]]; then
    check_version=$(ls /usr/local/lsws/$Website_chinh/html/web/phpmyadmin | grep 'RELEASE-DATE-' | sed 's/RELEASE-DATE-//g')
elif [[ -d /usr/local/lsws/$Website_chinh/html/phpmyadmin ]]; then
    check_version=$(ls /usr/local/lsws/$Website_chinh/html/phpmyadmin | grep 'RELEASE-DATE-' | sed 's/RELEASE-DATE-//g')
fi

phpmyadmin_version=5.2.1

if [[ $check_version = $phpmyadmin_version ]];then
echo "$ban_dang_su_dung_phien_ban_moi_nhat"
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "97" ]];then
. /etc/wptt/wptt-phpmyadmin-main 1
fi

if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-update-main 1
fi
exit
fi


if [[ $check_version != $phpmyadmin_version ]];then
echo "$xac_nhan $ban_co_muon update PhpMyadmin: "
prompt="$nhap_lua_chon_cua_ban [1-2]: "
dongy="n"
options=("$dong_y" "$khong_dong_y")

PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
			break
			;;
		*)
			printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
			break
			;;
	esac
done


if [[ $dongy = 'y' ]]; then
    _runing "$cap_nhat PhpMyAdmin $phien_ban $phpmyadmin_version"
    
    # Xóa thư mục phpmyadmin cũ
    if [[ -d /usr/local/lsws/$Website_chinh/html/web/phpmyadmin ]]; then
        rm -rf /usr/local/lsws/$Website_chinh/html/web/phpmyadmin
    elif [[ -d /usr/local/lsws/$Website_chinh/html/phpmyadmin ]]; then
        rm -rf /usr/local/lsws/$Website_chinh/html/phpmyadmin
    fi
    
    # Xóa thư mục tạm
    rm -rf /usr/local/lsws/phpmyadmin

    # Kiểm tra và tải phpMyAdmin vào đúng thư mục
    if [[ -d /usr/local/lsws/$Website_chinh/html/web ]]; then
        cd /usr/local/lsws/$Website_chinh/html/web
        wget -P /usr/local/lsws/$Website_chinh/html/web https://files.phpmyadmin.net/phpMyAdmin/$phpmyadmin_version/phpMyAdmin-$phpmyadmin_version-all-languages.zip --no-check-certificate >/dev/null 2>&1
        unzip -q /usr/local/lsws/$Website_chinh/html/web/phpMyAdmin-$phpmyadmin_version-all-languages.zip
        mv /usr/local/lsws/$Website_chinh/html/web/phpMyAdmin-$phpmyadmin_version-all-languages /usr/local/lsws/$Website_chinh/html/web/phpmyadmin
        rm -f /usr/local/lsws/$Website_chinh/html/web/phpMyAdmin-$phpmyadmin_version-all-languages.zip
        cp -f /usr/local/lsws/$Website_chinh/html/web/phpmyadmin/config.sample.inc.php /usr/local/lsws/$Website_chinh/html/web/phpmyadmin/config.inc.php
    else
        cd /usr/local/lsws/$Website_chinh/html
        wget -P /usr/local/lsws/$Website_chinh/html https://files.phpmyadmin.net/phpMyAdmin/$phpmyadmin_version/phpMyAdmin-$phpmyadmin_version-all-languages.zip --no-check-certificate >/dev/null 2>&1
        unzip -q /usr/local/lsws/$Website_chinh/html/phpMyAdmin-$phpmyadmin_version-all-languages.zip
        mv /usr/local/lsws/$Website_chinh/html/phpMyAdmin-$phpmyadmin_version-all-languages /usr/local/lsws/$Website_chinh/html/phpmyadmin
        rm -f /usr/local/lsws/$Website_chinh/html/phpMyAdmin-$phpmyadmin_version-all-languages.zip
        cp -f /usr/local/lsws/$Website_chinh/html/phpmyadmin/config.sample.inc.php /usr/local/lsws/$Website_chinh/html/phpmyadmin/config.inc.php
    fi

    # Tạo thư mục tạm và thêm cấu hình
    mkdir -p /usr/local/lsws/phpmyadmin
    secret=$(openssl rand -base64 32)
    
    if [[ -d /usr/local/lsws/$Website_chinh/html/web/phpmyadmin ]]; then
        echo "\$cfg['TempDir'] = '/usr/local/lsws/phpmyadmin';" >> /usr/local/lsws/$Website_chinh/html/web/phpmyadmin/config.inc.php
        echo "\$cfg['blowfish_secret'] = '$secret';" >> /usr/local/lsws/$Website_chinh/html/web/phpmyadmin/config.inc.php
    else
        echo "\$cfg['TempDir'] = '/usr/local/lsws/phpmyadmin';" >> /usr/local/lsws/$Website_chinh/html/phpmyadmin/config.inc.php
        echo "\$cfg['blowfish_secret'] = '$secret';" >> /usr/local/lsws/$Website_chinh/html/phpmyadmin/config.inc.php
    fi
fi
		#tuong thich ubuntu tuong thich nhom litespeed
if $(cat /etc/*release | grep -q "Ubuntu") ; then
tuong_thich_nhom_litespeed="nogroup"
else
tuong_thich_nhom_litespeed="nobody"
fi

chown -R nobody:$tuong_thich_nhom_litespeed /usr/local/lsws/phpmyadmin
if [[ -d /usr/local/lsws/$Website_chinh/html/web/phpmyadmin ]]; then
    chown -R nobody:$tuong_thich_nhom_litespeed /usr/local/lsws/$Website_chinh/html/web/phpmyadmin
elif [[ -d /usr/local/lsws/$Website_chinh/html/phpmyadmin ]]; then
    chown -R nobody:$tuong_thich_nhom_litespeed /usr/local/lsws/$Website_chinh/html/phpmyadmin
fi
chmod 555 /usr/local/lsws/phpmyadmin
_rundone "$cap_nhat PhpMyadmin $phien_ban $phpmyadmin_version"
fi
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "97" ]];then
. /etc/wptt/wptt-phpmyadmin-main 1
fi

if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-update-main 1
fi


